/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArtworkImage: typeof import('./../src/components/ArtworkImage.vue')['default']
    ExplicitnessIcon: typeof import('./../src/components/ExplicitnessIcon.vue')['default']
    Flex: typeof import('./../src/components/utils/Flex.vue')['default']
    HeadersCheckbox: typeof import('./../src/components/utils/HeadersCheckbox.vue')['default']
    HeadersFilter: typeof import('./../src/components/utils/HeadersFilter.vue')['default']
    Index: typeof import('@/views/index.vue')['default']
    Item: typeof import('@/views/track/[item].vue')['default']
    Json: typeof import('./../src/components/utils/Json.vue')['default']
    ListGroup: typeof import('./../src/components/utils/ListGroup.vue')['default']
    ListSorting: typeof import('./../src/components/utils/ListSorting.vue')['default']
    ObjectModifier: typeof import('./../src/components/utils/ObjectModifier.vue')['default']
    ProgressBar: typeof import('./../src/components/utils/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./../src/components/SearchBar.vue')['default']
    SettingsDial: typeof import('./../src/components/SettingsDial.vue')['default']
    StatusHandler: typeof import('./../src/components/utils/StatusHandler.vue')['default']
    UrlDataSearch: typeof import('./../src/components/UrlDataSearch.vue')['default']
  }
}
