/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/docs/': RouteRecordInfo<
      '/docs/',
      '/docs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/docs/comment': RouteRecordInfo<
      '/docs/comment',
      '/docs/comment',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/docs/settings': RouteRecordInfo<
      '/docs/settings',
      '/docs/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/download': RouteRecordInfo<
      '/download',
      '/download',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/track/[item]': RouteRecordInfo<
      '/track/[item]',
      '/track/:item',
      { item: ParamValue<true> },
      { item: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/views/docs/index.md': {
      routes:
        | '/docs/'
      views:
        | never
    }
    'src/views/docs/comment.md': {
      routes:
        | '/docs/comment'
      views:
        | never
    }
    'src/views/docs/settings.md': {
      routes:
        | '/docs/settings'
      views:
        | never
    }
    'src/views/download.vue': {
      routes:
        | '/download'
      views:
        | never
    }
    'src/views/settings.vue': {
      routes:
        | '/settings'
      views:
        | never
    }
    'src/views/track/[item].vue': {
      routes:
        | '/track/[item]'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
